### ISSUE TITLE
.env.example is poorly documented

### ISSUE THREAD

**Issue by ZenenTreadwell** [lnbits/lnbits#1026]
I'm having trouble figuring out how to make my account the admin on the server. I see there's an option in the .env file but it's unclear how the formatting works, or what value I need to be passing

**Comment by Bashy** [comment]
Hi, you need to create a wallet/user first, this will allow you to know your user/wallet id.

Notice that the url that opens your wallet contains `usr=ABCDE&wal=012345` then you can modify the `.env` file to change `LNBITS_ADMIN_USERS` var and set the `ABCDE` value so that you have this line in the `.env` file
`LNBITS_ADMIN_USERS=ABCDE`

**Comment by dni** [comment]
@ZenenTreadwell does that answer your issue? i close it for now, and reopen it if the issue persists.

there is also a Admin Extension, https://github.com/lnbits/lnbits/pull/553
