### ISSUE TITLE
Sending Payment does not confirm

### ISSUE THREAD

**Issue by rootzoll** [lnbits/lnbits#110]
I build on RaspiBlitz (so LND in the backend) from master. Funded a wallet with 10 sats (worked) and the tried to pay a invoice from satoshis.place for 1 pixel using the `SEND` option in my lnbits wallet.  satoshis.place confirmed that the payment was send (my pixel was paid) but the LNbits stays on this screen (processing) and I see a GET-request polling in the background (returning paid:false) ... never confirms the done payment on the LNbits side.

![Bildschirmfoto 2020-10-07 um 15 32 04](https://user-images.githubusercontent.com/2472225/95338414-3073dd80-08b3-11eb-9acc-ceed906941f4.png)

@fiatjaf is there some websocket thing not kicking in? And why is polling failing to get the correct result?

**Comment by fiatjaf** [comment]
No, there's not any websocket or new async stuff in this flow. This is more likely to be some bug I introduced in the `LndRestWallet` code. I'll take a look.

**Comment by fiatjaf** [comment]
The problem is that LND provides no way of checking that a single payment was completed.

On `LndWallet` we do this: https://github.com/lnbits/lnbits/blob/fc6e49b8218e1d21af41e9ac9714ae49d2da82a4/lnbits/wallets/lndgrpc.py#L114-L115

On `LndRestWallet` we list the last 20 payments and try to find the one we're looking for in there. Maybe in your case there were more than 20 payments after the one you were checking?

Anyway this is not an optimal solution.

**Comment by fiatjaf** [comment]
Actually no, it failed because the `reverse` parameter wasn't being passed, so LNbits is checking for the first 20 payments, not the last 20.

**Comment by fiatjaf** [comment]
There was still one other stupid bug.
