### ISSUE TITLE
Add support for different database backends

### ISSUE THREAD

**Issue by bumi** [lnbits/lnbits#121]
Currently lnbits only uses sqlite for persistence. 
To make it easier to run lnbits in different environments it would be great to support different database adapters. That relaxes the dependency on sqlite (which could still be the default) and allows people to use other DBs (like postgresql) that works for their setup.  

Potentially libraries we could use for that:
* [raw sqlalchemy](https://www.sqlalchemy.org/)
* [pugsql](https://github.com/mcfunley/pugsql)

Also related: #92

**Comment by fiatjaf** [comment]
Or https://www.encode.io/databases/, which @eillarra had suggested and works in async mode, and uses SQLAlchemy Core internally.

I liked that PugSQL though, I wish it had async support, and although I dislike ORMs I think they are our only hope here because our current queries are already incompatible with Postgres.

**Comment by bumi** [comment]
oh databases actually looks nice when we want to keep the SQL statements. (I personally like ORMs - I am more from the ruby world :D)
Which queries are incompatible with postgres? So far it seemed to me that most queries that I've seen are pretty standard.
