### ISSUE TITLE
[BUG] Topup button visible but request returns 401 unauthorized

### ISSUE THREAD

**Issue by bezysoftware** [lnbits/lnbits#1250]
**Describe the bug**
The "+" topup button is visible for an admin user (set via LNBITS_ADMIN_USERS env variable) but clicking it (specifying amount + enter) returns 401 unauthorized

**Expected behavior**
I expect the topup button to not even be visible when I do not have privileges to use it. Or it should work when it's visible

**Screenshots**
![image](https://user-images.githubusercontent.com/6108688/209833372-af0b7395-1219-4c1c-a092-45497a618a98.png)
![image](https://user-images.githubusercontent.com/6108688/209833341-705842fc-bf25-4e56-aa22-5b1674e7e1b5.png)

**Desktop (please complete the following information):**
 - LNbits version: 0.9.5.3

**Comment by talvasconcelos** [comment]
There's two possible routes for this! 
1. This shouldn't happen, and the 'plus' sign shouldn't show up unless you're a super user (which means you need to have Admin UI enabled) 
2. We should make it so that when the user/owner of the LNbits instance is not using the AdminUI this feature is available...

@dni @motorina0 ?

**Comment by dni** [comment]
yes, 1. + should only be visible with superuser, as @arcbtc decided.
2. that means regular admin are not allowed to topup.

@arcbtc is that ok? 
we could also change it so admins can also brrr.  so we do not have this issue when users are not using admin_ui
