### ISSUE TITLE
LNURL Pay Webhook

### ISSUE THREAD

**Issue by normandmickey** [lnbits/lnbits#144]
I am trying to flip a relay using an LNURL Pay invoice and an ESP32.  The ESP32 is running an ASync Server and I have it publicly exposed on port 81 for testing.  When I browse to "http://ipaddress:81/update?output=2&state=1" I can flip the relay on (state=0 turns it off).  But nothing happens when I set that as the Webhook URL for LNURLp and pay the invoice.

**Comment by fiatjaf** [comment]
What happens if you set the webhook URL to https://switch.free.beeceptor.com? The payload should appear at https://beeceptor.com/console/switch (this page must be open at the time the webhook is sent for it to be visible).

Also, consider joining https://t.me/lnbits if you want a more synchronous discussion medium.

**Comment by fiatjaf** [comment]
For future reference: as discussed in the chat, the cause seems to be that the server is expecting a GET request but LNURLp sends a POST.

**Comment by fiatjaf** [comment]
That was it, indeed.
