### ISSUE TITLE
Make it possible to override the `extensions` path

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#1579]
Currently, the path is hardcoded as `Path(settings.lnbits_path, "extensions")` but I think we should make it possible to override this path the same we we allow to override the data folder via `LNBITS_DATA_FOLDER`.

I propose to introduce `LNBITS_EXTENSIONS_FOLDER` setting which does that (can default to `./extensions`).
This will allow a system administrator to install LNbits into a read-only location (maybe they are using Nix which installs programs to immutable locations) and still allow installation of extensions in `/var/lib/lnbits/extensions` or some other mutable location.

**Comment by prusnak** [comment]
I think @afilini mentioned in https://github.com/lnbits/lnbits/pull/1574#issuecomment-1462149910 that he has some proof of concept for this? Would you please share this with us?

**Comment by motorina0** [comment]
Thanks for the request, it makes sense!
I will try to implement it this week.

**Comment by prusnak** [comment]
Another approach would be to store unpacked extensions in `{LNBITS_DATA_FOLDER}/extensions/` where we already store the downloaded ZIP files.

We would need to update `PYTHON_PATH` to reflect that location for finding the sources (but the same if true even if we had a separate `LNBITS_EXTENSIONS_FOLDER` variable).

**Comment by dni** [comment]
1 more thing to consider ```{LNBITS_DATA_FOLDER}``` is also currently zipped and downloaded when you perform the backup i recently introduced.

i think its fine, to put them in there, they will get a backup aswell and wont need to be redownloaded ;) after restoring.

**Comment by motorina0** [comment]
- I have started by using the `settings.lnbits_data_folder` as a default location for extensions
- the changes are simple, see: https://github.com/lnbits/lnbits/compare/overriede_extensions_path
- however, there is a problem with hardcoded paths in `__init__.py` (`StaticFiles` and `template_renderer`)
```py
tpos_static_files = [
    {
        "path": "/tpos/static",
        "app": StaticFiles(directory="lnbits/extensions/tpos/static"),
        "name": "tpos_static",
    }
]


def tpos_renderer():
    return template_renderer(["lnbits/extensions/tpos/templates"])
```
- making this change means that all extensions have to be touched in order to support it

**Comment by dni** [comment]
is it possible now?

**Comment by motorina0** [comment]
No, not yet.
I have not found a way for loading modules from outside the path of the python process.

**Comment by HaosGames** [comment]
Related to https://github.com/lnbits/lnbits/pull/1855
I figured out a way for it work anyway with nix by putting a symlink from the extensions folder to another mutable location. But this only works now if you install via nixos modules. 

There are however a few other hardcoded locations that I can't seem to fix because I can't figure out where exactly lnbits is trying to create them. Mainly the `.super-user` file and a `upgrade` folder.

**Comment by dni** [comment]
i think `.super_user` should go into `LNBITS_DATA_DIR` would that help?

**Comment by HaosGames** [comment]
That would help a lot. Being able to override the extension path could also be very helpful. That would make make lnbits able to run without installing it via nixos-modules but only building it with nix. That's because I am currently symlinking the extension folder via overriding a build phase in the nixos-module. That is not possible if you only build with nix as fa as I know.

**Comment by dni** [comment]
there you go https://github.com/lnbits/lnbits/pull/1900

**Comment by motorina0** [comment]
Unfortunately I still have no solution for this (loading the module from external path) :(
My WIP is [here](https://github.com/lnbits/lnbits/blob/import_external_module/lnbits/app.py#L301-L310)

**Comment by jackstar12** [comment]
> Unfortunately I still have no solution for this (loading the module from external path) :( My WIP is [here](https://github.com/lnbits/lnbits/blob/import_external_module/lnbits/app.py#L301-L310)

@motorina0 have you tried adding the extension path to `PYTHONPATH`? Its an env var which tells python where to look for imports

**Comment by motorina0** [comment]
> > Unfortunately I still have no solution for this (loading the module from external path) :( My WIP is [here](https://github.com/lnbits/lnbits/blob/import_external_module/lnbits/app.py#L301-L310)
> 
> @motorina0 have you tried adding the extension path to `PYTHONPATH`? Its an env var which tells python where to look for imports

I have only added the path to `sys.path` (https://docs.python.org/3/tutorial/modules.html#the-module-search-path)

```
import sys
sys.path.append('foo/bar')
```

**Comment by motorina0** [comment]
Implemented here: https://github.com/lnbits/lnbits/pull/1940

Closing this issue.
