### ISSUE TITLE
Server doesn't start in HTTPS despite LNBITS_FORCE_HTTPS=true

### ISSUE THREAD

**Issue by tradewind886** [lnbits/lnbits#158]
Is this normal behavior? where should I look if i want to make sure the server runs in HTTPS?

**Comment by fiatjaf** [comment]
LNbits itself doesn't run in HTTPS. You must use some proxy in front of it, which is the standard practice everywhere. Most people use nginx with certbot for automatic LetsEncrypt certificates, but we recommend https://caddyserver.com/.

**Comment by tradewind886** [comment]
thanks for clarifying :)

**Comment by tradewind886** [comment]
After playing around with this, im curious about the danger of exposing the api calls over HTTP.

does exposing an admin key compromise any of the other admin keys?  are there so many possible keys that it wouldn't even matter? Aren't the keys useless without the corresponding node ?

**Comment by fiatjaf** [comment]
What do you mean by "exposing"?

You have to send wallet keys when making a request, but doing that isn't "exposing" it. Exposing it would be printing it on a public webpage or something like that.

Each key is only bound to one LNbits wallet, so compromising one doesn't compromise the others. But the node has nothing to do with it. If I get a key to one of your LNbits wallets I can spend from it -- and only from it, not from the others.

However if you turn off your node or disconnect LNbits from it then my attempts to spend will fail because ultimately LNbits is using the node.
