### ISSUE TITLE
0.04btc bounty, JitsiPay, LN payment powered Jitsi chat extension 

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#211]
0.04btc bounty, 0.02btc from @arcbtc / 0.02btc from @MaxHillebrand

Extension that creates a jitsi link with the ability to send funds back/forth between participants in a jitsi chat, and trigger events when payment happens

ie:
Embed a lnurl-pay and a balance into each participants stream. 
Trigger a confetti gif when participant receives funds. 
Funds can be withdrawn via lnurl-withdraw or wallet link

Proposals for better workflows very welcome!

**Comment by MaxHillebrand** [comment]
I confirm the 0.02 btc bounty from my side. Thanks in advance for the hero who picks this up!

feature requests:

- every jitsi call participant can get paid.
- every jitsi call participant can pay others.
- listeners of a livestream of the jitsi call can pay participants [via scanning QR code, maybe, not sure if that will be possible to have the qr code for every participant visible all the time...] 
- payments can be done from an external wallet [scan qr code from phone wallet]
- payments can be done with an lnbits wallet [easy button click]
- payments per minute with a custom sat amount, either only when the participant is speaking, or even when he is silent.
- one-time boost payments with a custom sat amount.
- optionally a payment required to join the call as participant. This could even be split up, so that X% of the sent amount go directly to the organizer of the event as an upfront fee, while Y% are deposited into the participants lnbits wallet, for future payments in the call.
- at the end of the call, participants can withdrawl their sats to a different wallet, maybe they can stay in a long term lnbits wallet.

One potential problem that I see, is that jitsi participants are ephemeral and without long lived reputation. What will happen if a participant refreshes his browser, and appears as a new participant? He should still have the same lnbits wallet etc. 

Hopefully all of this can be done without changing jitsi code, or without requiring a self-hosted jitsi setup. It would be awesome if this can be done with ANY public jitsi server, or maybe even other call applications too!

**Comment by arcbtc** [comment]
Ooooo, good point!

You could store the wallet details in local-storage, then have the page check there first, is easy enough to do.

**Comment by MaxHillebrand** [comment]
- would be cool if the payee can also add a message to the boost, which is then displayed on screen, or at least shown to the organizer to bring it up. 
- maybe also a way that everyone sees the questions / messages, and can "upvote" with tossing some sats. Then the organizer can read the most upvoted question.

This is probably similar to an already extension, so maybe both can be combined in some way, or that there are just two pages for those different extensions.

**Comment by arcbtc** [comment]
Lets move any further discussion to the pr

**Comment by MaxHillebrand** [comment]
@nochiel @dni I'm so happy that this finally is happening! Thanks a bunch for implementing it, you guys rock.

I think now is a good time to payout the 4 mil bounty, please reach out to me to coordinate in DM. npub1klkk3vrzme455yh9rl2jshq7rc8dpegj3ndf82c3ks2sk40dxt7qulx3vt

**Comment by salemrashes3-hash** [comment]
``>>>>(¿
