### ISSUE TITLE
Feature Request: Fee splitting used as referral rewards. 

### ISSUE THREAD

**Issue by MoritzKa** [lnbits/lnbits#276]
As an operator of a LNbits server I want to onboard more users onto my server. Now Alice uses my LNbits already. If Alice onboards Bob on my LNbits, the transaction fees that are paid by Bob are split between me (the operator) and Alice (the referrer). 

I am also thinking about how LNbits could be used to build a simple cashback case for the local coffee shop: Each time I buy a coffee X% cashback are added to my LNBits wallet (provided by the shop); but I can only withdraw the money if a certain threshold is reached. That might incentivize me to come back and buy another coffee.

Both cases could incentivize the distribution and adoption of Lightning wallets. 

Happy to get your feedback.

**Comment by talvasconcelos** [comment]
I like the cashback idea, referral fee splitting not that much, and could be a cool way to promote use of lightning!

On a practical approach, multiple merchants possibly using the same LNbits provider could offer that cashback. because if everyone has it's own, users end up with 10 wallets, each with a few sats, scattered across a few merchants!
It's a good idea and could some more thought development!
