### ISSUE TITLE
"LN ticketing" pay-per-word ticketing

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#29]
A pay-per-word simple ticketing system,

The user sets a title, description, and price per word, which generates a frontend shareable form, consisting of email and a textbox. 

The customer fills out the form on the frontend and submits, which generates an invoice calculated on their queries word count. Once the customer pays the invoice the query is sent to the user's extension backend, and they reply via email.

Some example use cases are a professional translator sharing the link for PAYG translation services, an expert being asked questions, a fun tipping service.

**Comment by sgeisler** [comment]
So a bit like https://ln-ask.me/ but with per-word payment? @Kixunil

**Comment by Kixunil** [comment]
Sounds interesting, @sgeisler thanks for tagging me!

**Comment by arcbtc** [comment]
Yes, exactly that, although I had never heard of that service before, nice work @Kixunil !

**Comment by Kixunil** [comment]
Thanks!

**Comment by arcbtc** [comment]
If you have some spare time and want to make the extension, we could throw a 0.02btc your way, and you could get credit in the about etc

**Comment by Kixunil** [comment]
That sounds interesting. Is there any documentation on how the extension should work? Would it be enough to perform an API call to LN bits to get/check the invoice and maybe hook to web paths somehow?

**Comment by Kixunil** [comment]
Found the paywall example. I think I might be able to do it. I wonder if any of these have to be included:

* Admin interface for setting the texts, photos and rates (as opposed to just a simple config file)
* Some kind of cron job to automatically delete unpaid or old questions
* Major changes to the look of the interface
* Changes to the invoice handling (go and see how it looks on my site, you can see the invoice without paying. :))
* Using other mechanism for checking the invoice instead of polling (e.g. websocket)
* Fiat amounts for rates
* Configurable limits on size of the questions
* Tests

**Comment by arcbtc** [comment]
It should be simple, and in keeping with the style

User can make multiple frontends instances, just like paywall. 

User sets title, description, amount per word - a shareable frontend link is generated

I wouldn't overthink it too much.

**Comment by Kixunil** [comment]
> It should be simple, and in keeping with the style

You mean the code or UI?

**Comment by arcbtc** [comment]
The whole file, code, and UI, just adapt it to your needs

**Comment by Kixunil** [comment]
That sounds like more work than I expected, especially on frontend, where I'm not very efficient. Considering that I'd effectively give up some competitive advantage and I have some more important things to do right now, I'm currently unable to do it under these terms.

What I *would be* willing to do is:
* Single instance per user
* Same UI as I have at https://ln-ask.me
* Ridiculously trivial admin UI - just the list of questions, title, description, rate
* Code style as the paywall example

For the above mentioned price, I could do the above within a month, likely much sooner. It'd be more economical for someone more skilled in UI to do the UI changes. Obviously, that doesn't mean I would never do it otherwise, it'd just take indefinite amount of waiting.

**Comment by arcbtc** [comment]
That's cool man if you're busy don't worry. I'll have a crack this week. Will credit your project as inspiration as well, as you were there first
