### ISSUE TITLE
Websocket / webhook for invoice payment detection

### ISSUE THREAD

**Issue by Kukks** [lnbits/lnbits#30]
This seems like a cool project! I'm investigating adding support into BTCPay to use an LNBits based wallet for accepting lightning. We do however some form of push from the server to BTCPay to notify of an invoice being paid. 

On an unrelated note, are you publishing any docker images?

**Comment by sgeisler** [comment]
This will also reduce the load on the backend if users don't have to poll all the time. Most real node backends support some form of notification on payment finalization. For the ones that don't support that there could be a central thread polling all open payments and sending notifications instead of every request causing a separate poll.

**Comment by arcbtc** [comment]
WebSockets need to happen at some point, this is as good an excuse as any. 
Linking LNbits and BTCPay server is an exciting concept

**Comment by Kukks** [comment]
> 
> 
> WebSockets need to happen at some point, this is as good an excuse as any.
> Linking LNbits and BTCPay server is an exciting concept

Yes, I could integrate LNBits as if it was another lightning node in our lightning abstraction. Someone offering a BTCPay server to multiple merchants could then host LNBits alongside and use that as a way for them to accept lightning via their node!

Will need the websocket support and multiarch docker images though

**Comment by fiatjaf** [comment]
Hey, just a heads up: LNbits now has an (still undocumented while we make sure it works) SSE endpoint that you can listen to to get an event every time an invoice payment is received (it listens for notifications in the background from each of the funding sources -- except lntxbot), matches the incoming payments to each LNbits wallet and dispatches the event there.

`curl https://lnbits.example/api/v1/payments/sse -H 'x-api-key: yourkey'` should work. It will give you something like this:

```
curl 'http://localhost:5000/api/v1/payments/sse' -H 'x-api-key: 4b0518a9a640af02b5165fd9879a756c'
event: keepalive

event: payment
data: {"checking_id": "UeEG32TSDuKUzsxwUJupgX0Nlf8Ix9aElrDPGcmQzUU=", "pending": 0, "amount": 600000, "fee": 0, "memo": "an invoice", "time": 1602288389, "bolt11": "lnbcrt60n1p0cp7c9pp528ssdhmy6g8w99xwe3c9pxafs97sm90lprradpykkr83njvse4zsdqzyccqzpgxqzjcsp52439y3p0sg8mqvgrr5tfx56prq59nrmmq52cqjv09wr9c3kw35yq9qy9qsqfjv5egvze5dtl7n0dg24f533xdvvxm2w0u9l5pl3j79fvfknc05q02lxtggtd3rqsrgu6wyetyt0tgdhv78d38s4qljmvar00hux2dspcqq0k7", "preimage": "0000000000000000000000000000000000000000000000000000000000000000", "payment_hash": "51e106df64d20ee294cecc70509ba9817d0d95ff08c7d68496b0cf19c990cd45", "extra": {}, "wallet_id": "8fbefbdba16c4dd19afa641ebd51fd5e"}

event: keepalive

event: keepalive
```

I chose an SSE stream because it seems to be lighter and simpler to implement on every side, but WebSockets or Webhooks are also possible to do.

The code is here if anyone is curious: https://github.com/lnbits/lnbits/blob/2894944b1e43ce1faabb6142860f6be1db5655d3/lnbits/core/views/api.py#L134-L185
