### ISSUE TITLE
Questions related to Debian packaging

### ISSUE THREAD

**Issue by Kixunil** [lnbits/lnbits#33]
I'm working on packaging various Bitcoin stuff for Debian. You can see my project at https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/

I find `lnbits` to be a very interesting candidate for packaging. I have some questions that I need answers to before deciding on the priority and the proper approach:

* Does `lnbits` include some kind of master management interface for the server admin?
* ~~Can `lnbits` initialize `lnd` wallet?~~ No longer relevant
* Is it possible to configure prefix for web paths? e.g. `/lnbits/...` instead of `/...`, the intention is to avoid conflicts with other apps
* Is it possible to use configuration file instead of environment variables?
* Is it possible to use multiple LN nodes? I was thinking having one system-wide node and optionally other nodes for users (ideally more per user, so the users can have multiple Tor identities). Note: not a priority.
* Does `lnbits` support some kind of SSO natively?
* Are there any plans on making the UI less complicated? (e.g. hiding various hex strings behind "advanced" menu)

**Comment by tomichec** [comment]
I'm just looking into a way how to prefix web paths. Has anyone found an answer to that question?

**Comment by Kixunil** [comment]
@tomichec I didn't look into it yet as I was waiting for my questions to be answered.

I've update my issue to reflect current state of things. The repo is no longer experimental, but beta and I'm working on making it stable. I believe no more external packages will be added before stabilizing.

**Comment by fiatjaf** [comment]
Let me answer your questions here @Kixunil:

- **Does lnbits include some kind of master management interface for the server admin?** Not at this point.
- **Is it possible to configure prefix for web paths?** Shouldn't this be done by a proxy in front of LNbits? I'm not sure what LNbits should do to support this, but if there is something to do we should.
- **Is it possible to use configuration file instead of environment variables?** No, but you can always write the environment variables in a file and read it automatically when launching LNbits. I think that is done automatically by LNbits if the file is called `.env` and is located at the right place. I'm not exactly sure how this works because it's Python magic.
- **Is it possible to use multiple LN nodes?** We intend to support this, but it's not possible now.
- **Does lnbits support some kind of SSO natively?** No.
- **Are there any plans on making the UI less complicated?** No.

**Comment by tomichec** [comment]
> Is it possible to configure prefix for web paths? Shouldn't this be done by a proxy in front of LNbits? I'm not sure what LNbits should do to support this, but if there is something to do we should.

I think it is a good idea to support it within lnbits. It should not be too much work and it greatly simplifies this setting in a range of other application (like BTCPayServer besides cryptoanarchy-deb-repo). Also, many other apps do support it by default and the nginx package that would support it is not in the default nginx installation.

I have done some research into it and it seems that hypercorn should be able to do it. There is some [middleware dispatcher][dispatch], that should be able to do exactly that, but I haven't manage to make it work even with the simplest hello-world application.

[dispatch]: https://pgjones.gitlab.io/hypercorn/how_to_guides/dispatch_apps.html

I have also found some suggestions that [other packages][slack] could be used to do exactly that -- like Blueprint.

[slack]: https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes

There is already also an [issue][issue] that might be related, as it solves the proxy setup and suggestion is to use middleware instead of `lnbits/proxy_fix.py`

[issue]: https://github.com/lnbits/lnbits/issues/131

Perhaps the scope of the works is already enough to create another issue. What do you think?

**Comment by fiatjaf** [comment]
I think a pull request that both this and #131 is what we need :grin:

**Comment by Kixunil** [comment]
Thanks for the answers!

Using proxy is totally fine for me as long as the paths don't mess up. Some apps don't take into account the possibility of root path being different from `/` and thus don't work. I think all applications I've seen so far needed to be configured to know about the prefix (This is not a problem for me, the only thing I care about is for it to work at all.)

I asked about env because I've heard claims of it not being secure but I couldn't find an exploit myself. Anyway it shouldn't matter here as there's no confidential information in env, so that's OK.

> multiple LN nodes? We intend to support this

Good, my repo also has only one right now. Will try to coordinate in the future.

Would you accept a PR implementing SSO in the future? Would you be open to consider UI improvement ideas/PRs? I don't promise to do these things soon but they are something I'd be interested in looking into at some point.

**Comment by fiatjaf** [comment]
There is confidential information in the env, yes. Keys to your node, for example.
It shouldn't be hard to change that to allow using a config file. But I think that if you read the `.env` file from inside the process that is running LNbits it will be the same, the values won't be leaked to the rest of the system (if that is your concern). But don't quote me in any of this.

What kind of SSO do you have in mind? Currently LNbits work by just giving you an URL to your wallet and that URL has all your credentials in it.

**Comment by Kixunil** [comment]
I was thinking of optionally enabling LNbits for the owner of the server/whitelisted users only. The SSO was meant to resemble one present on ThunderHub - pass a single-use token in the URL.
