### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#48]
We need to add a login system to LNbits, but it must be done in a way that maintains instawallet functionality, so a user can use LNbits with/without a login. 

Once a user has opted to secure their account with a login, all  wallet?usr={uuid} will be redirected to /u/{uuid}/ (login protected). 

Let's figure out the best way to achieve this

**Comment by HamishMacEwan** [comment]
Firstly the beggared question, "Why do we need a login system?" should be addressed.

As you acknowledge and several denizens of https://t.me/lnbits noted, the current use cases exciting the most interest **require** no passwords for what you call "instawallets" and others "smart vouchers."

Before all the admin of passwords, users, security breaches,  etc is considered as a necessary its value needs consideration.

The wal and usr values are needles in separate galactic haystacks and protecting the URL is for the bearer to decide.

I've admired lnbits separation of concerns and as little as I understand a lot of these technologies, I have managed to cobble it together and make a small node of my own which is the kind of homesteading of the noosphere so long predicted.

Make a simple platform and things will emerge.  Don't solve all the problems, many you don't have.

At this point I think refinement and resilience rather than spreading over a broader range of tasks.  Do one thing.  Really really well.

https://jimmy.macewan.nz:50011/wallet?usr=b0562d017d9740a5afd0585aa3624964&wal=b449e1d4cfa84f46866c15d7c1a49e2e

**Comment by arcbtc** [comment]
I agree, but the option to use a traditional login has always been on the roadmap, the DB has always had fields for username/password. Login functionality can be added without losing any of the current features.
Thanks for the concern though, and I'm very glad you see LNbits value

**Comment by arcbtc** [comment]
Working on it here 
https://github.com/lnbits/lnbits/tree/Login

**Comment by capitalistdog** [comment]
What if instead of a login/pass, using derivation to generate API keys from superficially traditional credentials? 

A user could specify username and password, derivation then proves work to limit abuse and meet a key enrollment qualification.

I'd be interested in using LNbits as a "fallback" wallet in instances where liquidity or channels are not yet present in a non-custodial solution. This would be portable and enable wallets to automatically enroll new users.

**Comment by fiatjaf** [comment]
I think @capitalistdog has solved it: allow a username+password system, but only use these to generate a `usr` string deterministically.

**Comment by arcbtc** [comment]
Eventually it would be nice to have different ways to save wallets, starting with storing accounts on local-storage

![image](https://user-images.githubusercontent.com/33088785/123622115-c534b780-d803-11eb-855c-e41410ecf2f6.png)

and then on the frontpage we can have 

![image](https://user-images.githubusercontent.com/33088785/123622147-d1b91000-d803-11eb-8535-38230151c732.png)
