### ISSUE TITLE
type integer for field "amount" of table "apipayments" for postgres database is not enough

### ISSUE THREAD

**Issue by as-schug** [lnbits/lnbits#956]
While I try to migrate from sqlite3 to postgres, field amount from table apipayments is of type integer, but, value 3490661000 msats 
is above 2147483648 limit value for integer types

You should consider change that type to BIGINT...

**Comment by callebtc** [comment]
I have encountered this problem myself. My workaround was to use lnbits to create the tables in PG but don't migrate the data yet. I then changed the type of all amount columns to BIGINT manually and did the migration.

I think the problem is that we use a single schema for all db backends and they only share  the INT type (SQLite doesn't know BIGINT). 

Maybe sqlalchemy has a workaround for this but the one possibilty that i can think of would be to change the schema in migrations.py according to the backend used (BIGINT if PG, INT if not).

**Comment by as-schug** [comment]
> I have encountered this problem myself. My workaround was to use lnbits to create the tables in PG but don't migrate the data yet. I then changed the type of all amount columns to BIGINT manually and did the migration.
> 
> I think the problem is that we use a single schema for all db backends and they only share the INT type (SQLite doesn't know BIGINT).
> 
> Maybe sqlalchemy has a workaround for this but the one possibilty that i can think of would be to change the schema in migrations.py according to the backend used (BIGINT if PG, INT if not).

That´s what I did also.
Thanks for you explanation. I don´t know how it works inside lnbits source code...
